with open('components/LuxuryLiveFitting.tsx', 'r') as f:
    content = f.read()
content = content.replace('<button className="flex size-12 shrink-0 items-center justify-center rounded-full text-white/90" style={{ background: "rgba(10, 10, 10, 0.8)", backdropFilter: "blur(12px)", border: "1px solid rgba(255, 255, 255, 0.1)" }}>\n              <span className="material-symbols-outlined">photo_library</span>\n            </button>', '<button aria-label="Photo Library" className="flex size-12 shrink-0 items-center justify-center rounded-full text-white/90" style={{ background: "rgba(10, 10, 10, 0.8)", backdropFilter: "blur(12px)", border: "1px solid rgba(255, 255, 255, 0.1)" }}>\n              <span className="material-symbols-outlined">photo_library</span>\n            </button>')

content = content.replace('<button className="relative flex size-20 shrink-0 items-center justify-center rounded-full border-4 border-[#ecab13]/30 bg-white">\n                <div className="flex size-16 items-center justify-center rounded-full border-2 border-[#101922]/10">\n                  <span className="material-symbols-outlined text-4xl text-[#ecab13]">camera</span>\n                </div>\n              </button>', '<button aria-label="Take Photo" className="relative flex size-20 shrink-0 items-center justify-center rounded-full border-4 border-[#ecab13]/30 bg-white">\n                <div className="flex size-16 items-center justify-center rounded-full border-2 border-[#101922]/10">\n                  <span className="material-symbols-outlined text-4xl text-[#ecab13]">camera</span>\n                </div>\n              </button>')

content = content.replace('<button className="flex size-12 shrink-0 items-center justify-center rounded-full text-white/90" style={{ background: "rgba(10, 10, 10, 0.8)", backdropFilter: "blur(12px)", border: "1px solid rgba(255, 255, 255, 0.1)" }}>\n              <span className="material-symbols-outlined">refresh</span>\n            </button>', '<button aria-label="Refresh" className="flex size-12 shrink-0 items-center justify-center rounded-full text-white/90" style={{ background: "rgba(10, 10, 10, 0.8)", backdropFilter: "blur(12px)", border: "1px solid rgba(255, 255, 255, 0.1)" }}>\n              <span className="material-symbols-outlined">refresh</span>\n            </button>')

with open('components/LuxuryLiveFitting.tsx', 'w') as f:
    f.write(content)
