import React, { useState } from 'react';

export function ShareStoryButton({ imageUrl }: { imageUrl: string }) {
  const [isSharing, setIsSharing] = useState(false);

  const handleShare = async () => {
    setIsSharing(true);
    try {
      // In a real app, this would generate a composite image with the logo and trigger native share
      // For this implementation, we simulate the delay and trigger native share if available
      await new Promise(r => setTimeout(r, 1000));

      if (navigator.share) {
        await navigator.share({
          title: 'My S_FIT AI Virtual Fitting',
          text: 'Check out my new look generated by S_FIT AI!',
          url: window.location.href,
        });
      } else {
        alert('Sharing is not supported on this browser. In a native app, this would open Instagram Stories.');
      }
    } catch (err) {
      console.error('Error sharing:', err);
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <button
      onClick={handleShare}
      disabled={isSharing}
      className="mt-4 w-full py-3 bg-gradient-to-r from-pink-500 to-orange-500 hover:opacity-90 text-white rounded-xl text-sm font-bold flex items-center justify-center gap-2 transition-opacity"
    >
      <span>📸</span> {isSharing ? 'Preparing Story...' : 'Share to Story'}
    </button>
  );
}
