import React, { useRef } from 'react';
import Image from 'next/image';
import { motion } from 'framer-motion';

interface FittingResultProps {
  originalImage: string;
  resultImage: string;
  matchScore: number;
  onShare?: () => void;
  onRetake?: () => void;
}

export const FittingResult: React.FC<FittingResultProps> = ({
  resultImage,
  matchScore,
  onShare,
  onRetake,
}) => {
  const resultRef = useRef<HTMLDivElement>(null);

  const handleShareToStory = async () => {
    try {
      // Create a canvas to generate the branded vertical image
      const canvas = document.createElement('canvas');
      canvas.width = 1080;
      canvas.height = 1920; // Instagram Story standard 9:16 ratio
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      // Draw background (dark premium vibe)
      ctx.fillStyle = '#050505';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Add a subtle gradient
      const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
      gradient.addColorStop(0, '#111');
      gradient.addColorStop(1, '#000');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Load main result image
      const img = new window.Image();
      img.crossOrigin = "anonymous";
      img.src = resultImage;

      await new Promise((resolve) => {
        img.onload = resolve;
      });

      // Calculate dimensions to fit nicely within story ratio (with padding)
      const padding = 80;
      const targetWidth = canvas.width - (padding * 2);
      // Keep original aspect ratio
      const imgRatio = img.height / img.width;
      const targetHeight = targetWidth * imgRatio;

      const x = padding;
      const y = (canvas.height - targetHeight) / 2 - 100; // Shift up slightly

      // Draw image
      // Add subtle glow effect behind image
      ctx.shadowColor = '#007AFF'; // SFIT Blue
      ctx.shadowBlur = 50;
      ctx.fillStyle = '#000';
      ctx.fillRect(x, y, targetWidth, targetHeight);
      ctx.shadowBlur = 0; // Reset shadow

      ctx.drawImage(img, x, y, targetWidth, targetHeight);

      // Draw border around image
      ctx.strokeStyle = 'rgba(255,255,255,0.1)';
      ctx.lineWidth = 2;
      ctx.strokeRect(x, y, targetWidth, targetHeight);

      // Draw Header / Logo
      ctx.font = 'bold 60px "Helvetica Neue", Helvetica, Arial, sans-serif';
      ctx.fillStyle = '#FFFFFF';
      ctx.textAlign = 'center';
      ctx.fillText('S_FIT NEO', canvas.width / 2, y - 80);

      // Draw Match Score
      ctx.font = 'bold 40px monospace';
      ctx.fillStyle = '#007AFF';
      ctx.fillText(`${matchScore}% MATCH`, canvas.width / 2, y + targetHeight + 100);

      // Draw Footer
      ctx.font = '30px "Helvetica Neue", Helvetica, Arial, sans-serif';
      ctx.fillStyle = 'rgba(255,255,255,0.5)';
      ctx.fillText('Try it on at sfit.ai', canvas.width / 2, canvas.height - 100);

      // Convert to blob and share
      const dataUrl = canvas.toDataURL('image/png');

      // If Web Share API is available (Mobile/Safari)
      if (navigator.share) {
        const blob = await (await fetch(dataUrl)).blob();
        const file = new File([blob], 'sfit-tryon.png', { type: 'image/png' });
        await navigator.share({
          title: 'My Virtual Try-On',
          text: 'Check out my new look generated by S_FIT AI!',
          files: [file]
        });
      } else {
        // Fallback: trigger download
        const a = document.createElement('a');
        a.href = dataUrl;
        a.download = 'sfit-story.png';
        a.click();
      }

      if (onShare) onShare();
    } catch (err) {
      console.error('Error generating story image:', err);
    }
  };

  return (
    <div className="relative w-full max-w-md mx-auto overflow-hidden rounded-[var(--radius-lg)] border border-[var(--border-color)] bg-[var(--color-secondary)]">
      {/* AR Overlay UI */}
      <div className="relative aspect-[3/4]" ref={resultRef}>
        <Image
          src={resultImage}
          alt="Virtual Try-On Result"
          fill
          className="object-cover"
          sizes="(max-width: 768px) 100vw, 480px"
          unoptimized
        />

        {/* Scanning Line Animation */}
        <motion.div
          className="absolute inset-x-0 h-px bg-[var(--color-accent)] shadow-[0_0_10px_var(--color-accent)]"
          initial={{ top: "0%" }}
          animate={{ top: "100%", opacity: [0, 1, 0] }}
          transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
        />

        {/* HUD Elements */}
        <div className="absolute top-4 left-4">
          <div className="flex items-center gap-2 bg-black/40 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10">
            <div className="w-2 h-2 rounded-full bg-[var(--color-accent)] animate-pulse" />
            <span className="text-xs font-mono text-white">LIVE_FIT</span>
          </div>
        </div>

        <div className="absolute top-4 right-4">
           <div className="bg-black/40 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10">
            <span className="text-xs font-mono text-[var(--color-primary)]">
              {matchScore}% MATCH
            </span>
          </div>
        </div>

        {/* Corner Brackets */}
        <div className="absolute top-4 left-4 w-8 h-8 border-t-2 border-l-2 border-white/30 rounded-tl-lg" />
        <div className="absolute top-4 right-4 w-8 h-8 border-t-2 border-r-2 border-white/30 rounded-tr-lg" />
        <div className="absolute bottom-4 left-4 w-8 h-8 border-b-2 border-l-2 border-white/30 rounded-bl-lg" />
        <div className="absolute bottom-4 right-4 w-8 h-8 border-b-2 border-r-2 border-white/30 rounded-br-lg" />
      </div>

      {/* Actions */}
      <div className="p-4 flex gap-4 backdrop-blur-xl bg-black/80 absolute bottom-0 inset-x-0">
        <button
          onClick={onRetake}
          className="flex-1 py-3 px-4 rounded-full border border-[var(--border-color)] text-white text-sm font-medium hover:bg-white/10 transition-colors"
        >
          Retake
        </button>
        <button
          onClick={handleShareToStory}
          className="flex-1 py-3 px-4 rounded-full bg-[var(--color-primary)] text-[var(--color-secondary)] text-sm font-semibold hover:brightness-110 transition-all shadow-[var(--shadow-glow)] flex items-center justify-center gap-2"
        >
          <span className="material-symbols-outlined text-sm">share</span>
          Share to Story
        </button>
      </div>
    </div>
  );
};
