import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms';
}

export function LegalModal({ isOpen, onClose, type }: LegalModalProps) {
  const content = {
    privacy: {
      title: "Privacy Policy",
      text: "Your privacy is important to us. Photos uploaded to S_FIT AI are processed securely and temporarily for the sole purpose of virtual fitting. We do not store your photos permanently, nor do we share them with third parties or use them to train generalized AI models. All biometric and image data is deleted from our active servers immediately after your session ends."
    },
    terms: {
      title: "Terms of Service",
      text: "By using S_FIT AI, you agree to these terms. S_FIT AI provides virtual fitting visualizations which are generated by AI. While we strive for accuracy, actual physical fit may vary. The service is provided 'as is'. You may not use this service to upload prohibited content, including illegal, explicit, or copyright-infringing materials."
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/80 backdrop-blur-sm"
          />
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            className="relative w-full max-w-lg bg-[#111] border border-white/20 rounded-2xl p-6 shadow-2xl z-10 max-h-[80vh] flex flex-col"
          >
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold text-white">{content[type].title}</h2>
              <button
                onClick={onClose}
                className="text-gray-400 hover:text-white transition-colors"
                aria-label="Close"
              >
                ✕
              </button>
            </div>

            <div className="flex-1 overflow-y-auto pr-2 text-sm text-gray-300 leading-relaxed space-y-4">
              <p>{content[type].text}</p>
              {/* Dummy text for scrollable effect */}
              <p>Information Collection and Use: We collect information to provide better services to all our users. The types of personal information we collect are dependent on how you interact with our Services.</p>
              <p>Data Security: We work hard to protect you from unauthorized access, alteration, disclosure, or destruction of information we hold.</p>
              <p>Changes to this Policy: We may change this policy from time to time. We will not reduce your rights under this Privacy Policy without your explicit consent.</p>
            </div>

            <div className="mt-6 pt-4 border-t border-white/10 flex justify-end">
              <button
                onClick={onClose}
                className="px-6 py-2 bg-[#007AFF] hover:bg-[#005bb5] text-white font-bold rounded-lg transition-colors"
              >
                Understood
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
