import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function LegalModal({ isOpen, onClose }: LegalModalProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <motion.div
            className="relative w-full max-w-lg bg-void-black border border-white/20 rounded-xl overflow-hidden shadow-2xl flex flex-col max-h-[80vh]"
            initial={{ scale: 0.95, y: 20 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.95, y: 20 }}
          >
            <div className="p-4 border-b border-white/10 flex justify-between items-center">
              <h2 className="text-xl font-bold">Privacy Policy & Terms</h2>
              <button onClick={onClose} className="text-soft-gray hover:text-white">✕</button>
            </div>
            <div className="p-6 overflow-y-auto space-y-4 text-sm text-soft-gray">
              <h3 className="text-white font-bold">1. Data Privacy</h3>
              <p>Your photos are processed securely and temporarily for the sole purpose of virtual try-on. We do not store, share, or sell your biometric data to third parties.</p>
              <h3 className="text-white font-bold">2. Terms of Service</h3>
              <p>By using S_FIT AI, you agree to our terms. The virtual try-on results are generated by AI and may not perfectly reflect reality.</p>
              <h3 className="text-white font-bold">3. Acceptable Use</h3>
              <p>Users must not upload explicit, illegal, or copyrighted material without permission.</p>
              <p className="mt-4 italic">Last updated: Today</p>
            </div>
            <div className="p-4 border-t border-white/10">
              <button onClick={onClose} className="w-full py-3 bg-cyber-lime text-black font-bold rounded-lg hover:bg-[#aacc00] transition-colors">
                I Understand & Agree
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
