import React from 'react';

interface StoryShareButtonProps {
  imageUrl: string;
}

export function StoryShareButton({ imageUrl }: StoryShareButtonProps) {
  const handleShare = async () => {
    try {
      // Fetch the image to create a blob
      const response = await fetch(imageUrl);
      const blob = await response.blob();

      // Create a file from the blob
      const file = new File([blob], 'sfit-tryon.png', { type: blob.type });

      // Check if Web Share API is available and supports files
      if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          title: 'My S_FIT AI Try-On',
          text: 'Check out my new look generated by S_FIT AI!',
          files: [file],
        });
      } else {
        // Fallback: download the image
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = 'sfit-tryon.png';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        alert('Image downloaded! You can now share it to your story manually.');
      }
    } catch (error) {
      console.error('Error sharing image:', error);
      alert('Could not share image. Try downloading it instead.');
    }
  };

  return (
    <button
      onClick={handleShare}
      className="flex items-center gap-2 bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 hover:opacity-90 text-white px-4 py-2 rounded-lg font-bold text-sm transition-opacity shadow-lg"
    >
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="2" y="2" width="20" height="20" rx="5" ry="5" />
        <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
        <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" />
      </svg>
      Share to Story
    </button>
  );
}
