export const shareToStory = async (resultImage: string) => {
  try {
    const canvas = document.createElement('canvas');
    canvas.width = 1080;
    canvas.height = 1920;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Fill background
    ctx.fillStyle = '#050505';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw S_FIT Logo / Branding
    ctx.fillStyle = '#007AFF';
    ctx.font = 'bold 80px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('S_FIT NEO', canvas.width / 2, 200);

    ctx.fillStyle = '#FFFFFF';
    ctx.font = '40px Arial';
    ctx.fillText('Professional Virtual Fitting', canvas.width / 2, 260);

    // Load and draw the image
    const img = new Image();
    img.crossOrigin = 'anonymous'; // Prevent canvas tainting
    await new Promise((resolve, reject) => {
      img.onload = resolve;
      img.onerror = reject;
      img.src = resultImage;
    });

    // Calculate aspect ratio to fit inside canvas nicely
    const scale = Math.min((canvas.width - 200) / img.width, (canvas.height - 600) / img.height);
    const w = img.width * scale;
    const h = img.height * scale;
    const x = (canvas.width - w) / 2;
    const y = (canvas.height - h) / 2 + 50;

    // Draw image with rounded corners effect (using clip)
    ctx.save();
    ctx.beginPath();
    ctx.roundRect(x, y, w, h, 40);
    ctx.clip();
    ctx.drawImage(img, x, y, w, h);
    ctx.restore();

    // Draw footer text
    ctx.fillStyle = '#888888';
    ctx.font = '30px Arial';
    ctx.fillText('AI GENERATED', canvas.width / 2, canvas.height - 100);

    const dataUrl = canvas.toDataURL('image/png');

    // Attempt native share
    if (navigator.share) {
      const blob = await (await fetch(dataUrl)).blob();
      const file = new File([blob], 'sfit-story.png', { type: 'image/png' });
      await navigator.share({
        title: 'My S_FIT Virtual Try-On',
        text: 'Check out my new look generated by AI!',
        files: [file],
      });
    } else {
      // Fallback: download the image
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = 'sfit-story.png';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }
  } catch (err) {
    console.error('Error sharing to story:', err);
    alert('Failed to share to story. Please try again.');
  }
};
